import jsPDF from "jspdf";
import type { SeedAnalysis } from "@/data/seed-data";
import { getFindingTypeLabel } from "@/data/seed-data";

export function exportAnalysisPdf(analysis: SeedAnalysis) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
  };

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("CAE Analysis Report", margin, y);
  y += 12;

  // Company info
  doc.setFontSize(16);
  doc.text(analysis.company_name, margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Report Year: ${analysis.report_year}  |  Risk Level: ${analysis.overall_risk_level.toUpperCase()}  |  Risk Score: ${analysis.overall_risk_score}/100`, margin, y);
  y += 10;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Executive Summary
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("EXECUTIVE SUMMARY", margin, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const summaryLines = doc.splitTextToSize(analysis.summary, contentWidth);
  checkPage(summaryLines.length * 4 + 5);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 4 + 8;

  // Indonesia Status
  checkPage(20);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("INDONESIA STATUS", margin, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Indonesia Mentioned: ${analysis.indonesia_mentioned ? "YES" : "NO"}`, margin, y);
  y += 5;
  doc.text(`Status: ${analysis.indonesia_status.toUpperCase()}`, margin, y);
  y += 8;

  // Language Analysis
  checkPage(20);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("LANGUAGE ANALYSIS", margin, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Binding Commitments: ${analysis.binding_language_count}  |  Hedging Phrases: ${analysis.hedging_language_count}`, margin, y);
  y += 10;

  // Global Claim
  checkPage(20);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("GLOBAL CLAIM", margin, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const claimLines = doc.splitTextToSize(`"${analysis.global_claim}"`, contentWidth);
  doc.text(claimLines, margin, y);
  y += claimLines.length * 4 + 8;

  // Findings
  checkPage(15);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`ALL FINDINGS (${analysis.findings.length})`, margin, y);
  y += 8;

  analysis.findings.forEach((f, idx) => {
    checkPage(30);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`${idx + 1}. [${f.severity.toUpperCase()}] ${f.title}`, margin, y);
    y += 5;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(`Type: ${getFindingTypeLabel(f.finding_type)}${f.page_number > 0 ? `  |  Page: ${f.page_number}` : ""}${f.country_affected ? `  |  Country: ${f.country_affected}` : ""}`, margin, y);
    y += 4;
    const descLines = doc.splitTextToSize(f.description, contentWidth);
    checkPage(descLines.length * 3.5 + 5);
    doc.text(descLines, margin, y);
    y += descLines.length * 3.5;
    if (f.exact_quote) {
      const quoteLines = doc.splitTextToSize(`Evidence: "${f.exact_quote}"`, contentWidth - 5);
      checkPage(quoteLines.length * 3.5 + 5);
      doc.setFont("helvetica", "italic");
      doc.text(quoteLines, margin + 5, y);
      y += quoteLines.length * 3.5;
      doc.setFont("helvetica", "normal");
    }
    y += 6;
  });

  // Footer
  checkPage(15);
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text(`Generated by CAE (Corporate Accountability Engine) on ${new Date().toLocaleDateString()}`, margin, y);

  doc.save(`CAE_${analysis.company_name.replace(/[^a-zA-Z0-9]/g, "_")}_analysis.pdf`);
}
